/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { ApplicationContract } from "./Application";
import { CertificateContract } from "./Certificate";
import { CertificatesManagerContract } from "./CertificatesManager";
import { FacultiesManagerContract } from "./FacultiesManager";
import { FacultyContract } from "./Faculty";
import { InstituionsManagerContract } from "./InstituionsManager";
import { InstitutionContract } from "./Institution";
import { MigrationsContract } from "./Migrations";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Application"): ApplicationContract;
      require(name: "Certificate"): CertificateContract;
      require(name: "CertificatesManager"): CertificatesManagerContract;
      require(name: "FacultiesManager"): FacultiesManagerContract;
      require(name: "Faculty"): FacultyContract;
      require(name: "InstituionsManager"): InstituionsManagerContract;
      require(name: "Institution"): InstitutionContract;
      require(name: "Migrations"): MigrationsContract;
    }
  }
}

export { ApplicationContract, ApplicationInstance } from "./Application";
export { CertificateContract, CertificateInstance } from "./Certificate";
export {
  CertificatesManagerContract,
  CertificatesManagerInstance
} from "./CertificatesManager";
export {
  FacultiesManagerContract,
  FacultiesManagerInstance
} from "./FacultiesManager";
export { FacultyContract, FacultyInstance } from "./Faculty";
export {
  InstituionsManagerContract,
  InstituionsManagerInstance
} from "./InstituionsManager";
export { InstitutionContract, InstitutionInstance } from "./Institution";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
