/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface InstitutionContract
  extends Truffle.Contract<InstitutionInstance> {
  "new"(
    _instituionsManager: string,
    _id: number | BN | string,
    _name: string,
    sender: string,
    meta?: Truffle.TransactionDetails
  ): Promise<InstitutionInstance>;
}

type AllEvents = never;

export interface InstitutionInstance extends Truffle.ContractInstance {
  allowedModifiers(
    arg0: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  id(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  name(txDetails?: Truffle.TransactionDetails): Promise<string>;

  owner(txDetails?: Truffle.TransactionDetails): Promise<string>;

  update: {
    (_name: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(_name: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(
      _name: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _name: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  staffMember(
    _from: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ id: BN; name: string; active: boolean }>;

  listStaffMembers(
    _from: number | BN | string,
    skipInactive: boolean,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ id: BN; name: string; active: boolean }[]>;

  staffMembersLength(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  createStaffMember: {
    (_name: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(_name: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(
      _name: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _name: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  updateStaffMember: {
    (
      _staffMemberId: number | BN | string,
      _name: string,
      _active: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _staffMemberId: number | BN | string,
      _name: string,
      _active: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _staffMemberId: number | BN | string,
      _name: string,
      _active: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _staffMemberId: number | BN | string,
      _name: string,
      _active: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  listModifiers(
    _from: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string[]>;

  modifiersLength(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  addModifier: {
    (_modifier: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      _modifier: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _modifier: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _modifier: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  removeModifier: {
    (_modifier: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      _modifier: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _modifier: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _modifier: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  allowedToRemove(
    _sender: string,
    _toRemove: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  allowed(
    _modifierAddress: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  addCertificate: {
    (
      _certificate: string,
      _address: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _certificate: string,
      _address: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _certificate: string,
      _address: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _certificate: string,
      _address: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  issuedCertificates(
    _from: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string[]>;

  issuedCertificatesLength(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  pendingCertificatesLength(
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  pendingCertificates(
    _from: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string[]>;

  listFaculties(
    _from: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string[]>;

  facultiesLength(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  addFaculty: {
    (_faculty: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      _faculty: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _faculty: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _faculty: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  removeFaculty: {
    (_faculty: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      _faculty: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _faculty: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _faculty: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    allowedModifiers(
      arg0: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    id(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    name(txDetails?: Truffle.TransactionDetails): Promise<string>;

    owner(txDetails?: Truffle.TransactionDetails): Promise<string>;

    update: {
      (_name: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        _name: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _name: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _name: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    staffMember(
      _from: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ id: BN; name: string; active: boolean }>;

    listStaffMembers(
      _from: number | BN | string,
      skipInactive: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ id: BN; name: string; active: boolean }[]>;

    staffMembersLength(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    createStaffMember: {
      (_name: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        _name: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _name: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _name: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    updateStaffMember: {
      (
        _staffMemberId: number | BN | string,
        _name: string,
        _active: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _staffMemberId: number | BN | string,
        _name: string,
        _active: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _staffMemberId: number | BN | string,
        _name: string,
        _active: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _staffMemberId: number | BN | string,
        _name: string,
        _active: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    listModifiers(
      _from: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string[]>;

    modifiersLength(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    addModifier: {
      (_modifier: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        _modifier: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _modifier: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _modifier: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    removeModifier: {
      (_modifier: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        _modifier: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _modifier: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _modifier: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    allowedToRemove(
      _sender: string,
      _toRemove: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    allowed(
      _modifierAddress: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    addCertificate: {
      (
        _certificate: string,
        _address: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _certificate: string,
        _address: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _certificate: string,
        _address: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _certificate: string,
        _address: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    issuedCertificates(
      _from: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string[]>;

    issuedCertificatesLength(
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    pendingCertificatesLength(
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    pendingCertificates(
      _from: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string[]>;

    listFaculties(
      _from: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string[]>;

    facultiesLength(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    addFaculty: {
      (_faculty: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        _faculty: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _faculty: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _faculty: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    removeFaculty: {
      (_faculty: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        _faculty: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _faculty: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _faculty: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
